name = "SplitIterators"
uuid = "1ae6710d-7c1a-4308-aca3-ab3bbfdb2561"
authors = ["Felipe Noronha <felipenoris@gmail.com>"]
version = "0.1.0-dev"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
